export const SHIBA_GET_SHIBAS_REQUEST = 'SHIBA_GET_SHIBAS_REQUEST';
export const SHIBA_GET_SHIBAS_SUCCESS = 'SHIBA_GET_SHIBAS_SUCCESS';
export const SHIBA_GET_SHIBAS_FAILURE = 'SHIBA_GET_SHIBAS_FAILURE';
